// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWLqbeGMZQO5ystiU5_9sHAmbCei2hQQ',
    appId: '1:926802816232:web:9bd0dbc46c315469a0ed5d',
    messagingSenderId: '926802816232',
    projectId: 'coding-setup-c63de',
    authDomain: 'coding-setup-c63de.firebaseapp.com',
    storageBucket: 'coding-setup-c63de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8pFA5NBdGRLSUkjNPj5rXoiiaGAOkwZ4',
    appId: '1:926802816232:android:b12307a6abb99d26a0ed5d',
    messagingSenderId: '926802816232',
    projectId: 'coding-setup-c63de',
    storageBucket: 'coding-setup-c63de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUMj30mjnMNAsCFGawN79sgOJxErOzOdU',
    appId: '1:926802816232:ios:6b66a44ae733e158a0ed5d',
    messagingSenderId: '926802816232',
    projectId: 'coding-setup-c63de',
    storageBucket: 'coding-setup-c63de.appspot.com',
    iosBundleId: 'com.example.myCoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUMj30mjnMNAsCFGawN79sgOJxErOzOdU',
    appId: '1:926802816232:ios:7164d8df354b7fbda0ed5d',
    messagingSenderId: '926802816232',
    projectId: 'coding-setup-c63de',
    storageBucket: 'coding-setup-c63de.appspot.com',
    iosBundleId: 'com.example.myCoding.RunnerTests',
  );
}
